apiVersion: v1
kind: Service
metadata:
  name: leader-stream
  labels:
    app: leader-stream
spec:
  type: ClusterIP
  selector:
    app: leader-stream
  ports:
    - name: http
      port: 80
      targetPort: http
